// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturasSAP.Entities.Entities;

public partial class EmpresaGuia
{
    public int IdEmpresaGuia { get; set; }

    public string Descripcion { get; set; }

    public string CreadoPor { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime? FechaModificado { get; set; }

    public bool? EstadoEmpresa { get; set; }

    public string CodigoSAP { get; set; }

    public string ExpresionRegular { get; set; }
}