// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturasSAP.Entities.Entities;

public partial class PagoEncomienda
{
    public int IdPagoEncomienda { get; set; }

    public string CodigoSAP { get; set; }

    public int IdRetencionImpuesto { get; set; }

    public int IdTipoExoneradoSAP { get; set; }

    public bool Dolar { get; set; }

    public DateTime Fecha { get; set; }

    public DateTime FechaVencimiento { get; set; }

    public bool EnviadoSAP { get; set; }

    public bool? EstadoPagoEncomienda { get; set; }

    public string CreadoPor { get; set; }

    public DateTime FechaCreacion { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime FechaModificacion { get; set; }

    public virtual RetencionImpuestos IdRetencionImpuestoNavigation { get; set; }

    public virtual TipoExoneradoSAP IdTipoExoneradoSAPNavigation { get; set; }

    public virtual ICollection<PagoEncomiendaDetalle> PagoEncomiendaDetalle { get; set; } = new List<PagoEncomiendaDetalle>();
}