// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturasSAP.Entities.Entities;

public partial class Paises
{
    public int IdPais { get; set; }

    public string Pais { get; set; }

    public string CreadoPor { get; set; }

    public DateTime FechaCreacion { get; set; }

    public string ModifcadoPor { get; set; }

    public DateTime FechaModificacion { get; set; }

    public bool EstadoPais { get; set; }

    public string CodigoMap { get; set; }

    public string PaisEspaniol { get; set; }

    public virtual ICollection<PagoEncomiendaDetalle> PagoEncomiendaDetalle { get; set; } = new List<PagoEncomiendaDetalle>();
}