// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturasSAP.Entities.Entities;

public partial class ProveedorSAP
{
    public int IdProveedorSAP { get; set; }

    public int Code { get; set; }

    public int Name { get; set; }

    public string CodigoProveedor { get; set; }

    public string NombreProveedor { get; set; }

    public string TipoDocumento { get; set; }

    public string CAI { get; set; }

    public string Prefijo { get; set; }

    public DateTime FechaInicial { get; set; }

    public DateTime FechaVence { get; set; }

    public int NumeroInicial { get; set; }

    public int NumeroFinal { get; set; }

    public string RTN { get; set; }

    public int Serie { get; set; }

    public bool Estado { get; set; }

    public int NumeroCAI { get; set; }

    public DateTime FechaCreacion { get; set; }

    public string CreadoPor { get; set; }

    public DateTime FechaModificacion { get; set; }

    public string ModificadoPor { get; set; }
}