// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturasSAP.Entities.Entities;

public partial class tbPagoEncomiendum
{
    public int IdPagoEncomienda { get; set; }

    public int IdEmpresaGuia { get; set; }

    public string Factura { get; set; }

    public virtual tbEmpresaGuium IdEmpresaGuiaNavigation { get; set; }

    public virtual ICollection<tbPagoEncomiendaDetalle> tbPagoEncomiendaDetalles { get; set; } = new List<tbPagoEncomiendaDetalle>();
}