// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturasSAP.Entities.Entities;

public partial class tbPagoEncomiendaDetalle
{
    public int IdPagoEncomiendaDetalle { get; set; }

    public int IdPagoEncomienda { get; set; }

    public int IdTipoEncomienda { get; set; }

    public string Traking { get; set; }

    public decimal? Precio { get; set; }

    public virtual tbPagoEncomiendum IdPagoEncomiendaNavigation { get; set; }

    public virtual tbTipoEncomiendum IdTipoEncomiendaNavigation { get; set; }
}