// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturasSAP.Entities.Entities;

public partial class TipoEncomienda
{
    public int IdTipoEncomienda { get; set; }

    public string Descripcion { get; set; }

    public bool? EstadoPagoEncomienda { get; set; }

    public string CreadoPor { get; set; }

    public DateTime FechaCreacion { get; set; }

    public string ModificadoPor { get; set; }

    public DateTime FechaModificacion { get; set; }

    public virtual ICollection<PagoEncomiendaDetalle> PagoEncomiendaDetalle { get; set; } = new List<PagoEncomiendaDetalle>();
}